gems:
  - jekyll-seo-tag

#title: Змейка "Шаббатний хоровод"

title: Shabbat Snake

description: Старая добрая змейка, моделирующая шаббатние хороводы на Жмаченко. &#13;&#10;
    Игра поддерживает все устройства. Для управления на сматрфоне/планшете используйте соответствующие жесты в 
    любой области экрана, на компьютере - клавиши со стрелками.

url: https://alexeyandryukevich.github.io/ShabbatSnakeTest/

author: Alexey Andryukevich

logo: PostCover.png

image: PostCover.png